// <auto-generated />
using System;
using Auction.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Auction.Migrations
{
    [DbContext(typeof(AppDBContent))]
    [Migration("20190918173304_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Auction.Data.Models.Bid", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("increase");

                    b.Property<int?>("lotid");

                    b.Property<DateTime>("time");

                    b.Property<int?>("userid");

                    b.HasKey("id");

                    b.HasIndex("lotid");

                    b.HasIndex("userid");

                    b.ToTable("Bid");
                });

            modelBuilder.Entity("Auction.Data.Models.Lot", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("body");

                    b.Property<string>("desc");

                    b.Property<int>("drive");

                    b.Property<DateTime>("ending");

                    b.Property<double>("engineVolume");

                    b.Property<DateTime>("exposing");

                    b.Property<int>("fuel");

                    b.Property<string>("image");

                    b.Property<long>("mileage");

                    b.Property<string>("name");

                    b.Property<bool>("premium");

                    b.Property<long>("price");

                    b.Property<int>("transmission");

                    b.Property<int?>("userid");

                    b.Property<int>("year");

                    b.HasKey("id");

                    b.HasIndex("userid");

                    b.ToTable("Lot");
                });

            modelBuilder.Entity("Auction.Data.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("admin");

                    b.Property<string>("login");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.Property<string>("phoneNumber");

                    b.Property<DateTime>("registration");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Auction.Data.Models.Bid", b =>
                {
                    b.HasOne("Auction.Data.Models.Lot", "lot")
                        .WithMany("bids")
                        .HasForeignKey("lotid");

                    b.HasOne("Auction.Data.Models.User", "user")
                        .WithMany("bids")
                        .HasForeignKey("userid");
                });

            modelBuilder.Entity("Auction.Data.Models.Lot", b =>
                {
                    b.HasOne("Auction.Data.Models.User", "user")
                        .WithMany("lots")
                        .HasForeignKey("userid");
                });
#pragma warning restore 612, 618
        }
    }
}
